### ISSUE TITLE
Win 7

### ISSUE THREAD

**Issue by harryray33** [JuanBindez/DYGTube-Downloader-v2.11-rc1#1]
Does this work with ?

Thanks

**Comment by JuanBindez** [comment]
hello, if you use windows 10 or 11 go to the site dygtube.freesoftwarebrasil.com.br and click on windows10 will download the executable of the program, clicking on the executable will open the software, copy urls of Youtube videos and paste in the field and click on the download video or download MP3 button if you only want the audio, if you use Linux, you have the option Ubuntu already compiled too.

**Comment by JuanBindez** [comment]
if you use windows 7 you can try to compile the software with the step by step that is in the README.md file, remembering that this program is a software to download videos, songs and playlists.

**Comment by JuanBindez** [comment]
> Isso funciona com?
> 
> Obrigado

Hello harryray, I haven't tested it for win7, if you can test it and tell me if it worked, I'll be glad you contributed so I can put a download button for win7 on the site http://dygtube.freesoftwarebrasil.com.br

**Comment by JuanBindez** [comment]
> Does this work with ?
> 
> Thanks

Hello harryray, I haven't tested it for win7, if you can test it and tell me if it worked, I'll be glad you contributed so I can put a download button for win7 on the site http://dygtube.freesoftwarebrasil.com.br/
